# Rustfmt configuration - Modern defaults

edition = "2024"

# Imports
imports_granularity = "Crate"
group_imports = "StdExternalCrate"

# Formatting
max_width = 100
use_small_heuristics = "Default"
fn_call_width = 80
struct_lit_width = 80
struct_variant_width = 80
array_width = 80
chain_width = 80

# Style
newline_style = "Unix"
indent_style = "Block"
use_field_init_shorthand = true
use_try_shorthand = true
format_code_in_doc_comments = true
normalize_comments = true
wrap_comments = true
comment_width = 100

# Misc
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
